# 🧠 Emotional Engine Configuration

paths:
  input: input_output/
  output: input_output/storyline.txt

  modules:
    engine_boot: engine_boot/
    os_framework: emotional_os_framework/
    reflex: narrative_reflex_intelligence/
    geometry: emotional_geometry_layers/
    arc: story_line_arc/
    references: references/

  files:
    voice_input: voice_input.txt
    background: background.txt
    storyline: storyline.txt

runtime:
  enable_archetype: true
  enable_containment: true
  enable_somatic: true
  enable_reframe: true
  enable_dual_narrative: true
  log_session: true
  story_line_count: 100  # ← Add this line

grammar:
  emotional_grammar: emotional_grammar.json

scripts:
  engine: narrative_engine.py
  reflex: reflex_logic.py

logging:
  session_log: engine_boot/session_log.csv
  verbosity: high
  track_wheel_state: true
  track_reflex_trigger: true
  track_archetype_entry: true
  track_containment_success: true

defaults:
  fallback_wheel_state: neutral
  fallback_archetype: none
  fallback_containment: silent_hold
  fallback_somatic: breath_and_stillness



