model:
  name: "openai-gpt4"
  temperature: 0.7
  max_tokens: 800
  system_prompt: "You are a storytelling assistant."

storyline:
  lines: 20
  format: "dual narrative"
  include_classification: true
  classification_labels:
    - F1
    - F2
    - F3
    - M1
    - M2
    - M3
    - N/A

classification:
  enabled: true
  output_file: "classification.csv"
  fallback_label: "N/A"
  user_tracking: true
  session_label_format: "%a %b %d, %Y (%H:%M)"
  label_prefix: "Generated on"

emotional_grammar:
  enabled: true
  path: "emotional_grammar.json"
  grammar_mode: "semantic"
  use_expectation_map: true

reflex_logic:
  enabled: true
  path: "reflex_logic.py"
  mode: "archetype_shift"
  strategy: "dual_narrative"
  intensity: "moderate"

logging:
  enabled: true
  log_file: "copilot_log.txt"
  log_level: "info"
  anonymize: true


